version: '3'
volumes:
    todo-db-store:
services: 
    golang-api:
        build:
            context: todo
            dockerfile: Dockerfile
        tty: true
        volumes:
            - .:/go/src # .gitを含めるため
        stdin_open: true
    mysql:
        build:
            context: db
            dockerfile: Dockerfile
        tty: true
        environment: 
            - MYSQL_ROOT_PASSWORD=golang
        # ホストからDBを確認したい時用
        # ports:
        #     - "13306:3306"
        # composeネットワーク内でつなげる用
        expose:
            - "3306"
        volumes :
            # 初期データを投入するSQLが格納されているdir
            - ./db/init:/docker-entrypoint-initdb.d
            - todo-db-store:/var/lib/mysql
networks:
  default:
    external:
      name: backend